### ISSUE TITLE
toga-demo 'toga.constraint' error windows python3.5.2

### ISSUE THREAD

**Issue by LewisNeal** [pybee/toga-demo#7] opened 2016-09-26 12:44 UTC
executing toga-demo in command prompt gives the following error:

(VEpy35) C:\Users\lewis\VEpy35\Lib\site-packages>toga-demo
Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\users\lewis\VEpy35\Scripts\toga-demo.exe\__main__.py", line 5, in <module>
  File "c:\users\lewis\vepy35\lib\site-packages\toga_demo\__main__.py", line 6,
in <module>
    from .app import TogaDemo
  File "c:\users\lewis\vepy35\lib\site-packages\toga_demo\app.py", line 4, in <module>
    import toga
  File "c:\users\lewis\vepy35\lib\site-packages\toga\__init__.py", line 91, in <module>
    set_platform()
  File "c:\users\lewis\vepy35\lib\site-packages\toga\__init__.py", line 73, in set_platform
    locals['platform'] = importlib.import_module(module_name)
  File "C:\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\lewis\vepy35\lib\site-packages\toga_win32\__init__.py", line 7, in <module>
    from .widgets.button import *
  File "c:\users\lewis\vepy35\lib\site-packages\toga_win32\widgets\button.py", line 5, in <module>
    from .base import Widget
  File "c:\users\lewis\vepy35\lib\site-packages\toga_win32\widgets\base.py", line 3, in <module>
    from toga_cassowary.widget import Widget as CassowaryWidget
  File "c:\users\lewis\vepy35\lib\site-packages\toga_cassowary\widget.py", line
3, in <module>
    from toga.constraint import Attribute, Constraint
ImportError: No module named 'toga.constraint'

**Comment by freakboy3742** [comment] 2016-09-26 13:32
Thanks for the report. Toga support on Windows is lagging behind on other platforms, and the most recent updates to the core framework haven't been reflected on the Windows backend.

Closing as an effective duplicate of #4.

**Closed by freakboy3742** 2016-09-26 13:32 UTC

**Comment by LewisNeal** [comment] 2016-09-26 14:46
OK thanks for the update. I have been following the project and hope the improvements keep coming!
